---
title: "Exercise 1. Vectors"
author: "Lauren VanValkenburg"
date: "January 23, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Create the Vectors

#1a 
```{r}
c(1:20)
```
#1b
```{r}
c(20:1)
```
#1c 
```{r}
c(1:20, 19:1)
```
#1d
```{r}
tmp <- c(4, 6, 3)
```
#1e
```{r}
rep(tmp, times=10)
```
#1f
```{r}
rep(tmp, length=31)
```
#1g
```{r}
rep(tmp, times=c(10,20,30))
```

#2
```{r}
x <- seq(3.1, 6, by=.1)
exp(x)*cos(x)
```

#3a
```{r}
x <- .1
y <- .2
(x^seq(3,36,by=3))*(y^seq(1,34,by=3))
```
#3b
```{r}
f <- 2
(f^seq(1,25))/seq(1,25)
```

#4a
```{r}
i <- 10:100
sum(i^3+4*i^2)
```
#4b
```{r}
i <- 1:25
sum((2^i/i)+(3^i/i^2))
```

#5a
```{r}
paste(c("label"), 1:30)
```
#5b
```{r}
paste(c("fn"), 1:30, sep="")
```

#6
```{r}
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
```
#6a
```{r}
yVec[-1]-xVec[-length(xVec)]
```
#6b
```{r}
sin(yVec[-length(yVec)]) / cos(xVec[-1])
```
#6c
```{r}
xVecLen <- length(xVec)
xVec[-c(xVecLen-1,xVecLen)] + 2*xVec[-c(1,xVecLen)] - xVec[-c(1,2)]
```
#6d
```{r}
sum(exp(-xVec[-1])/(xVec[-length(xVec)]+10))
```

#7a
```{r}
yVec[yVec>600]
```
#7b
```{r}
(1:length(yVec))[yVec>600]
```
#7c
```{r}
xVec[yVec>600]
```
#7d
```{r}
sqrt(abs(xVec-mean(xVec)))
```
#7e
```{r}
sum(yVec>max(yVec)-200)
```
#7f
```{r}
sum(xVec%%2)
```
#7g
```{r}
xVec[sort(yVec)]
```
#7h
```{r}
yVec[c(T,F,F)]
```

#8
```{r}
1+sum(cumprod(seq(2,38,b=2)/seq(3,39,b=2)))
```
